# Configuration file for script "firmware_lock.py"
# You can find the latest version of the script and an example configuration file here:
# https://github.com/meraki/automation-scripts/tree/master/firmware_lock

general:
    # Your Meraki Dashboard API key. You can find more information about API keys here:
    # https://documentation.meraki.com/General_Administration/Other_Topics/Cisco_Meraki_Dashboard_API
    apiKey: 1234
    
    # Set applyToAllOrganizations to true to apply firmware lock settings to all organizations your API key can access
    # If set to true, organizationName will be ignored
    applyToAllOrganizations: false
    
    # If not using applyToAllOrganizations: true, edit the line below to match the name of the organization you want to lock
    organizationName: Big Industries Inc

    # Set runOnce to true to run the script once and exit (suitable for use in a cron job). If set to true, scanIntervalHours
    # will be ignored
    runOnce: false
    scanIntervalHours: 6
    
lockTrain:
    # Use the options below to lock a product type to a specific release train, or leave a value blank to have it unlocked.
    # Valid values:
    #   stable
    #   beta
    #   release candidate
    # If both a lockTrain and a lockVersion configuration is applied for a product type, lockVersion takes precedence
    MG:
    MR:
    MS:
    MT:
    MV:
    MX: stable
    
lockVersion:
    # Use the options below to lock a product type to a specific release version, or leave a value blank to have it unlocked.
    # If both a lockTrain and a lockVersion configuration is applied for a product type, lockVersion takes precedence
    MG:
    MR:
    MS:
    MT:
    MV:
    MX: 15.44
    